### ISSUE TITLE
Plugin doesn't work with blueprint file inputs

### ISSUE THREAD

**Issue by amaury-hanser** [david-szabo97/grav-plugin-admin-addon-media-rename#11]
Hello, 
I just installed the plugin via the admin panel.
When I try to rename a media it get stuck on "Renaming... (animated loader)".

When I open the console I see this error:
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data[En savoir plus]

Do you have any idea of what the problem might be ? 
Thanks in advance.

**Comment by david-szabo97** [comment]
Hi there!

I just did a test and everything works fine. Please open your developer tools and check what's returned by the request.

1. Edit page
2. Open Developer Tools -> Network
![image](https://user-images.githubusercontent.com/2256104/27827449-9f5b6878-60b7-11e7-8d08-cb86904a3de7.png)
3. Filter for 'rename'
4. Do a media rename
5. Open request
![image](https://user-images.githubusercontent.com/2256104/27827485-ca5947e8-60b7-11e7-819a-e4609514e20d.png)
6. Paste here the response. It must return `{}` for successful rename

Thank you!

**Comment by amaury-hanser** [comment]
Hello, 
Thanks for your time !
This is what I get:

![media-rename](https://user-images.githubusercontent.com/25964813/27828150-06256128-60bb-11e7-8498-79bafe040df2.png)

Edit: Oh, my mistake, and this is the response you asked:

---
```js
$(function() {
  ADMIN_ADDON_MEDIA_RENAME.renames = {};

  var clickedEle;
  var modal;
  var $modal;

  // Append modal
  $('body').append(ADMIN_ADDON_MEDIA_RENAME.MODAL);

  $(document).off('click', '[data-dz-name]');
  $(document).on('click', '[data-dz-name]', function(e) {
    clickedEle = $(this);
    modal = $.remodal.lookup[$('[data-remodal-id=modal-admin-addon-media-rename]').data('remodal')];
    $modal = modal.$modal;
    modal.open();

    // Populate fields
    var fileName = clickedEle.text();
    var name = fileName.substr(0, fileName.lastIndexOf('.'));
    var ext = fileName.substr(fileName.lastIndexOf('.') + 1);
    $('[name=old_name]', $modal).val(name);
    $('[name=old_ext]', $modal).val(ext);
    $('[name=new_name]', $modal).val(name);
    $('[name=new_ext]', $modal).val(ext);

    // Reset loading state
    $('.loading', $modal).addClass('hidden');
    $('.button', $modal).removeClass('hidden').css('visibility', 'hidden');
  });

  $(document).on('keyup', '[data-remodal-id=modal-admin-addon-media-rename] input', function(e) {
    var button = $('.button', $modal);
    var fields = ['name', 'ext'];

    var diff = false;
    fields.forEach(function(v) {
      var val1 = $('[name=new_'+v+']', $modal).val();
      var val2 = $('[name=old_'+v+']', $modal).val();

      if (val1 !== val2) {
        diff = true;
        return false;
      }
    });

    button.css('visibility', (diff) ? 'visible' : 'hidden');
  });

  $(document).on('click', '[data-remodal-id=modal-admin-addon-media-rename] .button', function(e) {
    $('.loading', $modal).removeClass('hidden');
    $('.button', $modal).addClass('hidden');
    
    var oldFileName = $('[name=old_name]', $modal).val() + '.' + $('[name=old_ext]', $modal).val();
    var newFileName = $('[name=new_name]', $modal).val() + '.' + $('[name=new_ext]', $modal).val();
    if (newFileName) {
      // Replace occurences in the editor
      var replaceInContent = $('[name=replace]:checked', $modal).val();
      if (replaceInContent == '1') {
        var editor = Grav.default.Forms.Fields.EditorField.Instance.editors.data('codemirror').doc;
        var re = /(\[[^\]]{0,}\])\(([^\)]{0,})\)/g;
        var res;
        var val = editor.getValue();
        var newVal = val;
        while ((res = re.exec(val)) !== null) {
          if (res[2] === oldFileName) {
            newVal = newVal.replace(res[0], res[1] + '(' + newFileName + ')');
          }
        }
        editor.setValue(newVal);
      }

      // Do request
      var replaceAll = $('[name=replace_all]:checked', $modal).val();
      var data = new FormData();
      data.append('media_path', clickedEle.closest('[data-media-local]').attr('data-media-local'));
      data.append('file_name', clickedEle.text());
      data.append('new_file_name', newFileName);
      data.append('replace_all', replaceAll);

      fetch(ADMIN_ADDON_MEDIA_RENAME.PATH, { method: 'POST', body: data, credentials: 'same-origin' })
        .then(res => res.json())
        .then(result => {
          if (result.error) {
            var alertModal = $.remodal.lookup[$('[data-remodal-id=modal-admin-addon-media-rename-alert]').data('remodal')];
            alertModal.open();
            $('p', alertModal.$modal).html(result.error.msg);
            return;
          }

          clickedEle.text(newFileName);
          modal.close();

          ADMIN_ADDON_MEDIA_RENAME.renames[data.get('file_name')] = newFileName;
        });
    }
  });
});

/**
 * Whenever a 'delmedia' task is called
 * via Fetch API, we intercept the requset
 * and we replace the old file name
 * with the new file name.
 */
(function(fetch) {
  window.fetch = function() {
    if (arguments[0].indexOf('delmedia') !== -1) {
      var data = arguments[1];
      var newName = ADMIN_ADDON_MEDIA_RENAME.renames[data.body.get('filename')];
      if (typeof newName !== 'undefined') {
        data.body.set('filename', newName);
      }
    }
    return fetch.apply(this, arguments);
  };

})(window.fetch);
```
---

**Comment by david-szabo97** [comment]
Strange the error is related to replacing links. Somewhy it can't find the editor's instance.

Can you try renaming the file with both rename feature toggled off? Thank you

**Comment by amaury-hanser** [comment]
I did, same thing.

I hadn't see it before, but I get a 404 for http://localhost/admin/admin-addon-media-rename

I installed the plugin directly in the admin panel, could it be linked ?

**Comment by david-szabo97** [comment]
Are you using the latest Grav core and Admin plugin?

**Comment by amaury-hanser** [comment]
Yes

**Comment by david-szabo97** [comment]
When you manually open http://localhost/admin/admin-addon-media-rename what happens?

`{"error":{"msg":"Invalid input"}}` this should be the response for that

**Comment by amaury-hanser** [comment]
http://localhost/admin/admin-addon-media-rename is not a correct path, so I get a 404.
It should be:
http://localhost/charitybackpackers/admin/admin-addon-media-rename
If I manually access this one, I get `{"error":{"msg":"Invalid input"}}`

**Comment by david-szabo97** [comment]
Oh I see. I will push a fix today or more likely tomorrow.

Thank you!

**Comment by amaury-hanser** [comment]
Amazing, thank you !

**Comment by david-szabo97** [comment]
Please update to v1.4.1 and let me know whether it fixed it or not.

I ran some tests and it went through so hopefully it will work fine.

**Comment by amaury-hanser** [comment]
Hello, 

Sorry but I got this error now:
Grav.default.Forms.Fields.EditorField.Instance.editors.data(...) is undefined

**Comment by david-szabo97** [comment]
Now that's a strange one :smile: 
Can you send me the list of the installed plugins?

**Comment by amaury-hanser** [comment]
If I choose:
Update links on this page No
Update links on all pages No
I get:
Failed to rename media
File not found

Here is the list of the installed plugins:

> Admin Panel v1.4.2
> Admin Addon Media Rename v1.4.1
> Customadmin v1.0.0
> DevTools v1.0.5
> Email v2.6.0
> Error v1.6.0
> Form v2.7.0
> Login v2.3.2
> Markdown Notices v1.0.0
> Problems v1.4.7

**Comment by david-szabo97** [comment]
Could you send me the result of this?

```js
console.log(document.getElementById('grav-dropzone').outerHTML);
console.log(ADMIN_ADDON_MEDIA_RENAME.PATH);
console.log(Grav.default.Forms.Fields.EditorField.Instance.editors);
```

Just copy-paste it into the console and you will get something like this.

![image](https://user-images.githubusercontent.com/2256104/27910752-c7d88bfa-6256-11e7-88d7-ef30df0915d8.png)

**Comment by amaury-hanser** [comment]
Well:
```
console.log(document.getElementById('grav-dropzone').outerHTML);
console.log(ADMIN_ADDON_MEDIA_RENAME.PATH);
console.log(Grav.default.Forms.Fields.EditorField.Instance.editors);
VM470:1 Uncaught TypeError: Cannot read property 'outerHTML' of null
    at <anonymous>:1:53
(anonymous) @ VM470:1
```

I have no clue what I've done wrong :/

**Comment by david-szabo97** [comment]
Wow.
Can you give me a screenshot? :smile:

```js
console.log(document.querySelector('html').outerHTML);
```

This will give you a huge string, you can save the console's content via right click -> save as

**Comment by amaury-hanser** [comment]
![error-rename](https://user-images.githubusercontent.com/25964813/27914857-b671e3d0-6264-11e7-9856-d1b738910781.jpg)

```
16:00:54,482 <html class="remodal-is-locked" lang="en"><head>
            <meta charset="utf-8">
        <title>Edit _slider01 | Charity Backpackers, hotel in Bodhgaya India</title>
                    <meta name="description" content="">
                            <meta name="robots" content="noindex, nofollow">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="icon" type="image/png" href="/charitybackpackers/user/plugins/admin/themes/grav/images/favicon.png">

                                                        <link href="/charitybackpackers/user/plugins/markdown-notices/assets/notices.css?608fbafa9d" type="text/css" rel="stylesheet">
<link href="/charitybackpackers/user/plugins/admin/themes/grav/css/codemirror/codemirror.css?608fbafa9d" type="text/css" rel="stylesheet">
<link href="/charitybackpackers/user/plugins/admin/themes/grav/css-compiled/nucleus.css?608fbafa9d" type="text/css" rel="stylesheet">
<link href="/charitybackpackers/u[…] 1

```

**Comment by david-szabo97** [comment]
That truncated the result =(
Do you have any sensitive data in your website? Could you zip your website and send me privately? You can send it to my email: david.szabo97@gmail.com

Otherwise, can you send me a screenshot when you are editing the page? (modals closed)
The issue is related to the page media dropzone somewhy. 

Firefox truncates the result of the line I sent you. Can you copy-paste the outer content of the HTML tag?
Inspect tab -> right click `<html lang="en">` -> copy -> outer

I'm running out of ideas 😞

**Comment by david-szabo97** [comment]
Can you give v1.5.0 a try? :smile:

**Comment by amaury-hanser** [comment]
Aaaaaaand.... It works like a charm ! 
I like the 

> Please don't forget to save the page, otherwise the rename will fail and it can't be automatically reverted.

Guess what ? I didn't save the page on my first try ! 😛 
Thank you very much for the fix !

**Comment by david-szabo97** [comment]
Great! My thanks that we could improve the plugin!
