### ISSUE TITLE
Call to a member function route() on null

### ISSUE THREAD

**Issue by SimpleByDesign** [david-szabo97/grav-plugin-admin-addon-media-rename#13]
Hi,

I inadvertently deleted my home page whilst playing with my test site and the following error message is thrown:

> Whoops \ Exception \ ErrorException (E_ERROR)
> Call to a member function route() on null

The issue is on line 134 in the file admin-addon-media-rename/admin-addon-media-rename.php. The line in question is, the issue is that $page doesn't exist:

`$jsConfig = ['PATH' => rtrim($this->grav['uri']->rootUrl(true), '/') . '/' . trim($this->getPath(), '/') . '/' . $page->route() . '/task:adminAddonMediaRenameDoRename', 'MODAL' => $modal];`

If I alter the function from:

```
  public function onTwigExtensions() {
    $modal = $this->grav['twig']->twig()->render('rename-modal.twig.html', $this->config->get('plugins.admin-addon-media-rename.modal'));
    $page = $this->grav['admin']->page(true);
      $jsConfig = ['PATH' => rtrim($this->grav['uri']->rootUrl(true), '/') . '/' . trim($this->getPath(), '/') . '/' . $page->route() . '/task:adminAddonMediaRenameDoRename', 'MODAL' => $modal];
      $this->grav['assets']->addInlineJs('var ADMIN_ADDON_MEDIA_RENAME = ' . json_encode($jsConfig) . ';', -1000, false);
      $this->grav['assets']->addCss('plugin://admin-addon-media-rename/admin-addon-media-rename.css', -1000, false);
      $this->grav['assets']->addJs('plugin://admin-addon-media-rename/admin-addon-media-rename.js', -1000, false);
  }
```

To

```
  public function onTwigExtensions() {
    $modal = $this->grav['twig']->twig()->render('rename-modal.twig.html', $this->config->get('plugins.admin-addon-media-rename.modal'));
    $page = $this->grav['admin']->page(true);
    if( $page ){
      $jsConfig = ['PATH' => rtrim($this->grav['uri']->rootUrl(true), '/') . '/' . trim($this->getPath(), '/') . '/' . $page->route() . '/task:adminAddonMediaRenameDoRename', 'MODAL' => $modal];
      $this->grav['assets']->addInlineJs('var ADMIN_ADDON_MEDIA_RENAME = ' . json_encode($jsConfig) . ';', -1000, false);
      $this->grav['assets']->addCss('plugin://admin-addon-media-rename/admin-addon-media-rename.css', -1000, false);
      $this->grav['assets']->addJs('plugin://admin-addon-media-rename/admin-addon-media-rename.js', -1000, false);
    }
  }
```

This fixes the issue around the fact a page is not returned. The change also blocks adding the scripts to the admin pages, as these break with javascript errors when page->route() is null.

Disabling the add-on also works, allowing you to add a new home page, then re-enabling the add-on everything works fine.

Best Wishes,
Matthew

**Comment by david-szabo97** [comment]
Hi there!
Well that's an interesting edge case :smile:

Thank you for reporting the bug!
Released v1.6.2 to fix the issue.
