### ISSUE TITLE
Add move-page feature

### ISSUE THREAD

**Issue by Flamenco** [david-szabo97/grav-plugin-admin-addon-media-rename#14]
I added a 'move page' action to your plugin.  Not sure if you are interested in a PR for that, or if I should just release a new plugin using your js workarounds.

<img width="222" alt="screen shot 2018-01-30 at 2 54 09 pm" src="https://user-images.githubusercontent.com/819940/35588175-d24705e2-05cd-11e8-954f-55cf38d6825f.png">

<img width="671" alt="screen shot 2018-01-30 at 2 54 20 pm" src="https://user-images.githubusercontent.com/819940/35588181-d5d3c204-05cd-11e8-8cac-f3f0c2fa5b6b.png">

**Comment by david-szabo97** [comment]
@Flamenco 

I feel like it's better if a plugin only has one purpose. Maybe we could rename the plugin and add more functionalities like yours. If you don't mind, create a PR and just add it to this plugin. Later we can decide how to make sure it doesn't confuse people.

Thanks!

**Comment by Flamenco** [comment]
The main issue is that I want to addon to the media div, but there is no API for it.  I just squeezed mine above yours using 'hacks' for now.  IMO it would be best to create an API for extending the media div (through official PR).

Also, current state of the my move functionality does not rename markdown references.

**Comment by Flamenco** [comment]
I took your 'I feel like it's better if a plugin only has one purpose' statement and created a plugin that does nothing but lets you add actions to the media bin.  I made sure it would wrap horizontally after 5 items so as to not step on admin-addon-media-rename toes.

https://github.com/Flamenco/grav-admin-media-actions

![53cff1ffe5018bae7fa4d06713c5f929cc422166-media-with-sample-actions](https://user-images.githubusercontent.com/819940/35783478-d9ad45e2-09d5-11e8-97a4-e515a0fd376c.png)
