### ISSUE TITLE
ADMIN_ADDON_MEDIA_RENAME is not defined in latest grav admin beta

### ISSUE THREAD

**Issue by Flamenco** [david-szabo97/grav-plugin-admin-addon-media-rename#16]
In the latest beta of grav admin the addJs throws an error because ADMIN_ADDON_MEDIA_RENAME is not defined.

Removing the `false`  from addInlineJs fixes it for me.

```
        $this->grav['assets']->addInlineJs('var ADMIN_ADDON_MEDIA_RENAME = ' . json_encode($jsConfig) . ';', -1000);
        $this->grav['assets']->addCss('plugin://admin-addon-media-rename/admin-addon-media-rename.css', -1000, false);
        $this->grav['assets']->addJs('plugin://admin-addon-media-rename/admin-addon-media-rename.js', -1000, false);
```

**Comment by douglasgough** [comment]
I'm also having this problem. When the plugin is enabled, it throws this error and it stops you from installing plugins at admin/plugins/install.

**Comment by andrewfenn** [comment]
Hi, not sure if this is the same issue but didn't want to start a new issue without confirming here first..

Getting JS error when installing the plugin and going to the Configuration screen..

> Uncaught ReferenceError: ADMIN_ADDON_MEDIA_RENAME is not defined

![screenshot from 2019-02-26 11-28-42](https://user-images.githubusercontent.com/409265/53387499-b7fc2980-39b9-11e9-911a-8c2ffb50032a.png)

v1.6.2 of the plugin. Grav v1.6.0-rc.3 - Admin v1.9.0-rc.3
