### ISSUE TITLE
Plugin Update not possible on Grav 1.6.x

### ISSUE THREAD

**Issue by jgate** [david-szabo97/grav-plugin-admin-addon-media-rename#17]
The issue is still available. It is not possible to update plugin since Grav 1.6.x

Getting JS error when installing the plugin and going to the Configuration screen..

Uncaught ReferenceError: ADMIN_ADDON_MEDIA_RENAME is not defined

**Comment by david-szabo97** [comment]
@jgate Disable the plugin first, update it and turn it back on.

**Comment by david-szabo97** [comment]
v1.6.3 fixes this.
