### ISSUE TITLE
Plugin doesn't work with Folder Numeric Prefix

### ISSUE THREAD

**Issue by monovertex** [david-szabo97/grav-plugin-admin-addon-media-rename#9]
From what I've seen, when the request is sent from the admin frontend, it sends the path without its numeric prefix (i.e. `/home`, instead of `/01.home`), which causes a not found error.

If I disable the numeric prefix for the page I'm trying to rename media on it does work, but I can't leave the page without a numeric prefix.

Any ideas on how to fix this or what's happening?

**Comment by david-szabo97** [comment]
Thank you for the bug report!

1.2.4 should fix this.
